### PR TITLE
Updates of the class file that may be of use

### PR DESCRIPTION
**Pull request by iroghair**
I made a few changes to the class file, adding ORCID, bibliographies, photo alignment fix and extended the number of timeline nodes. Added an example resume for multiple pages. The John Hammond example still works fine too.

### CODE REVIEW

**Comment by iroghair** [comment]
Found a mistake in the Orcid URL, so I need to reopen this PR

**Comment by iroghair** [comment]
Added another commit, reopened.

**Comment by Slyces** [comment]
Hi @iroghair. I love the work you've done, especially the mock-resume which is much better than the one I had made.

As for the changes you're implementing, I'd be happy to merge them. As long as the functionalities I focused on (single page, no picture) are not impacted, offering more flexibility for other use cases is obviously welcome.

I only have one concern about the new `readme.md`, we might want to revisit this a bit more if we merge your changes into main. Potentially look into releasing versions to indicate what's been introduced.

I'll look a bit more into the latex sometimes this week :)

**Comment by iroghair** [comment]
Hi @Slyces , thanks for your message. The mock-up resume was largely built by ChatGPT but I needed some page filling to show how to create follow-up pages.
You might be able to cherry-pick only the additions to the class file (e.g. not the style enhancements), but I'm not sure how to achieve that from a PR. For instance the addition of Orcid, the Google Maps link, the optional argument for cventries and the bug fix of the photo placement are non-breaking changes. I changed some font sizes, that may be personal preference and can be left out.
Cheers!

**Pull request closed without merging**
